wandb_version: 1

booster:
  value: gblinear
colsample_bytree:
  value: 2
grow_policy:
  value: lossguide
learning_rate:
  value: 1
max_depth:
  value: 9
max_leaves:
  value: 15
n_estimators:
  value: 63
reg_lambda:
  value: 14
sampling_method:
  value: uniform
subsample:
  value: 1
