wandb_version: 1

booster:
  value: gblinear
colsample_bytree:
  value: 2
grow_policy:
  value: lossguide
learning_rate:
  value: 1
max_depth:
  value: 10
max_leaves:
  value: 20
n_estimators:
  value: 70
reg_lambda:
  value: 4
sampling_method:
  value: uniform
subsample:
  value: 1
