wandb_version: 1

booster:
  value: gbtree
colsample_bytree:
  value: 3
grow_policy:
  value: lossguide
learning_rate:
  value: 1
max_depth:
  value: 2
max_leaves:
  value: 17
n_estimators:
  value: 62
reg_lambda:
  value: 21
sampling_method:
  value: uniform
subsample:
  value: 2
