wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.13
    start_time: 1669483285.755828
    t:
      1:
      - 5
      - 6
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 35
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.13
      5: 0.13.3
      8:
      - 2
      - 5
booster:
  desc: null
  value: gbtree
colsample_bytree:
  desc: null
  value: 0.3762841690216908
grow_policy:
  desc: null
  value: lossguide
learning_rate:
  desc: null
  value: 1
max_depth:
  desc: null
  value: 4
max_leaves:
  desc: null
  value: 2
n_estimators:
  desc: null
  value: 20
reg_lambda:
  desc: null
  value: 0.6342033446299761
sampling_method:
  desc: null
  value: uniform
subsample:
  desc: null
  value: 0.6502167879752103
