wandb_version: 1

booster:
  value: gbtree
colsample_bytree:
  value: 0.30075099138319084
grow_policy:
  value: depthwise
learning_rate:
  value: 1
max_depth:
  value: 3
max_leaves:
  value: 4
n_estimators:
  value: 79
reg_lambda:
  value: 10
sampling_method:
  value: uniform
subsample:
  value: 0.4075921706864142
