wandb_version: 1

booster:
  value: gblinear
colsample_bytree:
  value: 0.19702075744256864
grow_policy:
  value: lossguide
learning_rate:
  value: 1
max_depth:
  value: 19
max_leaves:
  value: 8
n_estimators:
  value: 63
reg_lambda:
  value: 1
sampling_method:
  value: uniform
subsample:
  value: 0.10682915226711363
