wandb_version: 1

booster:
  value: gblinear
colsample_bytree:
  value: 0.5
grow_policy:
  value: depthwise
learning_rate:
  value: 0.0001
max_depth:
  value: 12
max_leaves:
  value: 10
n_estimators:
  value: 50
reg_lambda:
  value: 1.0e-08
sampling_method:
  value: uniform
subsample:
  value: 0.3
