wandb_version: 1

booster:
  value: dart
colsample_bytree:
  value: 0.5
grow_policy:
  value: lossguide
learning_rate:
  value: 0.01
max_depth:
  value: 20
max_leaves:
  value: 6
n_estimators:
  value: 70
reg_lambda:
  value: 1.0e-05
sampling_method:
  value: uniform
subsample:
  value: 0.5
