wandb_version: 1

booster:
  value: gblinear
colsample_bytree:
  value: 0.5
grow_policy:
  value: lossguide
learning_rate:
  value: 0.0001
max_depth:
  value: 10
max_leaves:
  value: 20
n_estimators:
  value: 50
reg_lambda:
  value: 0.01
sampling_method:
  value: uniform
subsample:
  value: 0.8
