wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.13
    start_time: 1669499253.48711
    t:
      1:
      - 5
      - 6
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 35
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.13
      5: 0.13.3
      8:
      - 2
      - 5
booster:
  desc: null
  value: gbtree
colsample_bytree:
  desc: null
  value: 0.053763452616420127
grow_policy:
  desc: null
  value: depthwise
learning_rate:
  desc: null
  value: 1
max_depth:
  desc: null
  value: 0
max_leaves:
  desc: null
  value: 16
n_estimators:
  desc: null
  value: 53
reg_lambda:
  desc: null
  value: 3
sampling_method:
  desc: null
  value: uniform
subsample:
  desc: null
  value: 0.6003771530350259
