wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.13
    start_time: 1669399989.564435
    t:
      1:
      - 1
      - 5
      - 6
      - 53
      - 55
      2:
      - 1
      - 5
      - 6
      - 53
      - 55
      3:
      - 23
      4: 3.8.13
      5: 0.13.3
      8:
      - 1
      - 2
      - 5
