wandb_version: 1

booster:
  value: dart
colsample_bytree:
  value: 0.34681774492883444
grow_policy:
  value: depthwise
learning_rate:
  value: 1
max_depth:
  value: 16
max_leaves:
  value: 17
n_estimators:
  value: 50
reg_lambda:
  value: 4.923957219309006
sampling_method:
  value: uniform
subsample:
  value: 0.4342201991973677
