wandb_version: 1

booster:
  value: dart
colsample_bytree:
  value: 0.3727112861098774
grow_policy:
  value: lossguide
learning_rate:
  value: 1
max_depth:
  value: 9
max_leaves:
  value: 1
n_estimators:
  value: 42
reg_lambda:
  value: 4.734890714600473
sampling_method:
  value: uniform
subsample:
  value: 0.9990366710925656
