wandb_version: 1

booster:
  value: gbtree
colsample_bytree:
  value: 0.788308489071512
grow_policy:
  value: lossguide
learning_rate:
  value: 1
max_depth:
  value: 10
max_leaves:
  value: 4
n_estimators:
  value: 92
reg_lambda:
  value: 0.4707431957856567
sampling_method:
  value: uniform
subsample:
  value: 0.996367367870244
