wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.13
    start_time: 1669484243.502757
    t:
      1:
      - 5
      - 6
      - 35
      - 53
      - 55
      2:
      - 5
      - 6
      - 35
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.13
      5: 0.13.3
      8:
      - 2
      - 5
booster:
  desc: null
  value: dart
colsample_bytree:
  desc: null
  value: 0.36294797086807695
grow_policy:
  desc: null
  value: lossguide
learning_rate:
  desc: null
  value: 1
max_depth:
  desc: null
  value: 11.105298726047751
max_leaves:
  desc: null
  value: 2.2028220087936057
n_estimators:
  desc: null
  value: 30.871020737415055
reg_lambda:
  desc: null
  value: 2.403560871980759
sampling_method:
  desc: null
  value: uniform
subsample:
  desc: null
  value: 0.8052906471557624
