wandb_version: 1

booster:
  value: dart
colsample_bytree:
  value: 0.25803739356142386
grow_policy:
  value: lossguide
learning_rate:
  value: 1
max_depth:
  value: 2
max_leaves:
  value: 20
n_estimators:
  value: 20
reg_lambda:
  value: 4.558746497252859
sampling_method:
  value: uniform
subsample:
  value: 0.3029706347260942
