wandb_version: 1

booster:
  value: gbtree
colsample_bytree:
  value: 0.3762841690216908
grow_policy:
  value: lossguide
learning_rate:
  value: 1
max_depth:
  value: 4
max_leaves:
  value: 2
n_estimators:
  value: 20
reg_lambda:
  value: 0.6342033446299761
sampling_method:
  value: uniform
subsample:
  value: 0.6502167879752103
