wandb_version: 1

booster:
  value: dart
colsample_bytree:
  value: 0.3837413027337264
grow_policy:
  value: lossguide
learning_rate:
  value: 1
max_depth:
  value: 10
max_leaves:
  value: 15
n_estimators:
  value: 10
reg_lambda:
  value: 3.403110253815096
sampling_method:
  value: uniform
subsample:
  value: 0.4695150638997231
