wandb_version: 1

booster:
  value: gbtree
colsample_bytree:
  value: 0.3359813320514504
grow_policy:
  value: depthwise
learning_rate:
  value: 1
max_depth:
  value: 12
max_leaves:
  value: 2
n_estimators:
  value: 100
reg_lambda:
  value: 1.890917499257343
sampling_method:
  value: uniform
subsample:
  value: 0.38842820359043617
