wandb_version: 1

booster:
  value: gbtree
colsample_bytree:
  value: 0.35115831458226643
grow_policy:
  value: lossguide
learning_rate:
  value: 1
max_depth:
  value: 10
max_leaves:
  value: 6
n_estimators:
  value: 20
reg_lambda:
  value: 0.9276235854611536
sampling_method:
  value: uniform
subsample:
  value: 0.3021161882703779
